var api_url=config_api_url;var players_url=config_players_url;var vip_auto_upgrade=config_vip_auto_upgrade;var vip_price_day=config_vip_price_day;var vip_price_week=config_vip_price_week;var vip_price_month=config_vip_price_month;var vip_price_year=config_vip_price_year;var vodShowHtml_remove_add;var arr_History=new Array();var isneed_addpageid=1;var this_page_historyID=0;$(document).on("pageInit",function(e,pageId,$page){if(isneed_addpageid==1){this_page_name=pageId;if(arr_History[this_page_historyID+1]!=this_page_name){if(this_page_historyID+1<arr_History.length){arr_History=arr_History.slice(0,this_page_historyID+1);this_page_historyID=arr_History.length;arr_History.push(pageId);}else{this_page_historyID=arr_History.length;arr_History.push(pageId);}}else{this_page_historyID=this_page_historyID+1;}}
isneed_addpageid=1;if(this_page_historyID<1){$(".Goback").addClass("go_disable");}
else{$(".Goback").removeClass("go_disable");}
if(this_page_historyID>=arr_History.length-1){$(".Goforward").addClass("go_disable");}
else{$(".Goforward").removeClass("go_disable");}
if(pageId=="page_played"){localStorage_update_played();}
if(pageId=="page_fav"){localStorage_update_fav();u_fav_list();}});function Goback(){isneed_addpageid=0;if(this_page_historyID<1){$.toast("没法后退了哦");}else{this_page_historyID=this_page_historyID-1;console.log("goback pageInit"+this_page_historyID+" pageId "+arr_History[this_page_historyID]);$.router.load("#"+arr_History[this_page_historyID]);}}
function Goforward(){isneed_addpageid=0;if(this_page_historyID>=arr_History.length-1){$.toast("没法前进了哦");}else{this_page_historyID=this_page_historyID+1;console.log("Goforward pageInit"+this_page_historyID+" pageId "+arr_History[this_page_historyID]);$.router.load("#"+arr_History[this_page_historyID]);}}
function gotopage(Str_goto){$.closePanel();$.router.load(Str_goto,false,'left');}
$(document).on('click','.FAQ-dark',function(){$.alert('<div style="text-align: left;">自动跟随系统的显示模式自动切换暗黑模式，也可以手动切换</div>','切换说明');});if(window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches){$.cookie('themebody','1',{expires:180,path:'/'});CheckDark();}else{$("body").removeClass("theme-dark");$("#theme-dark").prop("checked",false)
$.cookie('themebody','0',{expires:180,path:'/'});}
let media=window.matchMedia('(prefers-color-scheme: dark)');let callback=(e)=>{let prefersDarkMode=e.matches;if(prefersDarkMode){$.cookie('themebody','1',{expires:180,path:'/'});CheckDark();}else{$("body").removeClass("theme-dark");$("#theme-dark").prop("checked",false)
$.cookie('themebody','0',{expires:180,path:'/'});}};if(typeof media.addEventListener==='function'){media.addEventListener('change',callback);}else if(typeof media.addListener==='function'){media.addListener(callback);}
function CheckDark(){if(($.cookie('themebody')==1)){$("body").addClass("theme-dark");$("#theme-dark").prop("checked",true)}else{$("body").removeClass("theme-dark");$("#theme-dark").prop("checked",false)}}
$("input[name='theme-dark']").on("change",function(){var change=$("#theme-dark").is(':checked');if(change){$.cookie('themebody','1',{expires:180,path:'/'});CheckDark();$.toast("已切换到黑夜模式");}else{$.cookie('themebody','0',{expires:180,path:'/'});CheckDark();$.toast("已取消黑夜模式");return false;}})
$(document).on('click','.loginout',function(){var buttons1=[{text:'确定要退出登录吗???',label:true},{text:'确定退出',onClick:function(){localStorage.removeItem("u_info");set_getinfo(0,0);$.router.load("#page-login");$.toast("已退出，请重新登录");}}];var buttons2=[{text:'取消',bg:'danger'}];var groups=[buttons1,buttons2];$.actions(groups);});$(function(){setTimeout(function(){$(".hidden5s").hide();},3000);})
$(document).on('click','.keywords span',function(){$("#searchinput").val($(this).html());});function search(){var keywd=$("#searchinput").val();var pattern=new RegExp("['#$%^&*()<>=]");if(keywd!=""&&keywd!=null){if(pattern.test(keywd)){$.alert('搜索关键词中有非法字符，请重新输入');$("#searchinput").attr("value","");$("#searchinput").focus();return false;}else{searchJsong(keywd);}}
else{$.toast("请输入关键词");$("#searchinput").focus();return false;}}
function searchJsong(keywd){localStorage_searchwd(keywd);$.ajax({url:api_url+"/api.php?ac=u_search&wd="+keywd,type:"post",dataType:"json",data:$('#userinfo_local').serialize(),beforeSend:function(){$.showPreloader('搜索 '+keywd+' ...');},success:function(r){if(r.code==1){$.hidePreloader();var json_rows_temp=r.list;var json_limitlength=json_rows_temp.length;if(json_limitlength>0){$("#page-search #listpic").show();$('#page-search #listpicTitle').html("搜索 “"+keywd+"” 共搜索到"+json_limitlength+"数据");$('#page-search #search_Show_li').html("");localStorage.removeItem("searchList");localStorage.setItem("searchList",JSON.stringify(json_rows_temp));for(var json_i=0;json_i<json_limitlength;json_i++){Json_To_piclist_html(json_rows_temp[json_i],json_i,"#search_Show_li","search");}
Check_and_modify();}
else{$("#listpic").hide();$.toast("没有搜索到影片，请留言返回或检查网络设置");}}
else{$.toast("提示："+r.code+" "+r.msg);}},error:function(){$.hidePreloader();$.toast("无法搜索服务器错误");},complete:function(){$.hidePreloader();}});setTimeout(function(){$.hidePreloader();},15000);}
function Json_To_piclist_html(Json_row,json_i,append_To,fromLoalStorage){$('#listpic_html_li .item-media').html('<img src="'+Json_row.vod_pic+'">');$('#listpic_html_li .item-title').html(Json_row.vod_name);$('#listpic_html_li .item-after').html(Json_row.vod_year);$('#listpic_html_li .daoyan').html(Json_row.vod_area+" "+Json_row.vod_lang+" "+Json_row.vod_director);$('#listpic_html_li .yanyuan').html(Json_row.vod_actor);$('#listpic_html_li .jieshao').html(Json_row.vod_content);$("#listpic_html_li .link").attr("onclick","open_vod_fromJson("+json_i+",'"+fromLoalStorage+"');");$("#listpic_html_li #thisvod").attr("class","vodid_"+Json_row.vod_id);$("#listpic_html_li .addfav").attr("onclick","u_fav_add("+Json_row.vod_id+");");$("#listpic_html_li .delfav").attr("onclick","u_fav_del("+Json_row.vod_id+");");$(append_To).append($("#listpic_html_li").html());}
function open_vod_fromJson(json_i,fromLoalStorage){var JSON_searchList
if(fromLoalStorage=="search"){JSON_searchList=JSON.parse(localStorage.getItem("searchList"));}
if(fromLoalStorage=="played"){JSON_searchList=JSON.parse(localStorage.getItem("played"));}
if(fromLoalStorage=="u_fav_list"){JSON_searchList=JSON.parse(localStorage.getItem("u_fav_list"));}
if(vodShowHtml_remove_add){$("#Show_vodFromJson_to_html").empty();$("#Show_vodFromJson_to_html").append(vodShowHtml_remove_add);}
$("#Show_vodFromJson_to_html #play_vod").addClass("Show_Vod_to_guest_class");$('#Show_vodFromJson_to_html h1').html("正在播放 "+JSON_searchList[json_i].vod_name);$('.vod_name').html(JSON_searchList[json_i].vod_name);$('#Show_vodFromJson_to_html .pianming').html(JSON_searchList[json_i].vod_name);$('#Show_vodFromJson_to_html .bieming').html(JSON_searchList[json_i].vod_sub);$('#Show_vodFromJson_to_html .daoyan').html(JSON_searchList[json_i].vod_director);$('#Show_vodFromJson_to_html .zhuyan').html(JSON_searchList[json_i].vod_actor);$('#Show_vodFromJson_to_html .shangying').html(JSON_searchList[json_i].vod_year+" "+JSON_searchList[json_i].vod_area+" "+JSON_searchList[json_i].vod_lang);$('#Show_vodFromJson_to_html .vodcontent').html(JSON_searchList[json_i].vod_content);if(JSON_searchList[json_i].vod_down_url!=""){var arr_AllDownUrl=JSON_searchList[json_i].vod_down_url.split("#")
var temp_DownURl="";$.each(arr_AllDownUrl,function(){temp_DownURl=temp_DownURl+this.split("$")[1]+"<br />";});$('#Show_vodFromJson_to_html .AllDownUrl').html(temp_DownURl);}
var Play_From="";var Play_urls="";if(JSON_searchList[json_i].vod_play_from==""){$('#Show_vodFromJson_to_html .PlayAllButtons .buttons-tab').html("本视频暂只能下载后观看");}else{var reg_from=new RegExp('\\$\\$\\$',"g");var Arr_Play_From=JSON_searchList[json_i].vod_play_from.replace(reg_from,',').split(",");var is_frist=0;var frist_frome;$.each(players_url,function(players_url_i,thispaly){$.each(Arr_Play_From,function(i){if($.trim(thispaly[0])==$.trim(this)){is_frist=is_frist+1;if(is_frist==1){frist_frome=i;Play_From='<a href="#PlayUrl_'+this+'" class="tab-link active button ">'+thispaly[1]+'</a>';}
else{Play_From=Play_From+'<a href="#PlayUrl_'+this+'" class="tab-link  button">'+thispaly[1]+'</a>';}}});});$('#Show_vodFromJson_to_html .PlayAllButtons .buttons-tab').html(Play_From);}
var temp_this;var Arr_vod_play_url=JSON_searchList[json_i].vod_play_url.split('$$$');var temp_this_url="";$('#Show_vodFromJson_to_html .PlayAllButtons .tabs').empty();$.each(Arr_vod_play_url,function(i){if(i==frist_frome){Play_urls='<div id="PlayUrl_'+Arr_Play_From[i]+'" class="fenji tab active">';}
else{Play_urls='<div id="PlayUrl_'+Arr_Play_From[i]+'"  class="fenji tab">';}
$.each(this.split("#"),function(ii){temp_this=this.split("$");temp_this_url=temp_this[1];Play_urls=Play_urls+'<a href="javascript:void(0);"  onclick="PlaysThisUrl(this,'+json_i+',&apos;'+fromLoalStorage+'&apos;)" class="button buttonmin " data-url="'+temp_this_url+'" data-from="'+Arr_Play_From[i]+'" data-name="'+JSON_searchList[json_i].vod_name+'" data-jishu="'+temp_this[0]+'">'+temp_this[0]+'</a>';});Play_urls=Play_urls+'<div class="clear"></div>';Play_urls=Play_urls+'</div>';$('#Show_vodFromJson_to_html .PlayAllButtons .tabs').append(Play_urls);});var Show_vodFromJson_to_html=$("#Show_vodFromJson_to_html").html();$("#Show_Vod_to_guest").empty();$("#Show_Vod_to_guest").append(Show_vodFromJson_to_html);$("#Show_vodFromJson_to_html #play_vod").removeClass("Show_Vod_to_guest_class");vodShowHtml_remove_add=$("#Show_vodFromJson_to_html #play_vod").detach();$.popup('.Show_Vod_to_guest_class');localStorage_played("","",JSON_searchList[json_i]);if(JSON_searchList[json_i].vod_down_url!=""==""){$("#Show_Vod_to_guest #downloadbutton").detach();$("#Show_Vod_to_guest .downloadtab").detach();}}
function close_play_vod_popup(){$("#iframe_palyer").attr("src","");$.closeModal('.Show_Vod_to_guest_class');$("#Show_Vod_to_guest_class").remove();}
function PlaysThisUrl(buttonthis,json_i,fromLoalStorage){var JSON_searchList
if(fromLoalStorage=="search"){JSON_PlaysThisUrl=JSON.parse(localStorage.getItem("searchList"));}
if(fromLoalStorage=="played"){JSON_PlaysThisUrl=JSON.parse(localStorage.getItem("played"));}
if(fromLoalStorage=="u_fav_list"){JSON_PlaysThisUrl=JSON.parse(localStorage.getItem("u_fav_list"));}
$(".fenji a").removeClass("button-fill");$(buttonthis).addClass("button-fill");$("#Show_Vod_to_guest_class h1").html("正在播放 "+$(buttonthis).attr("data-jishu")+" "+$(buttonthis).attr("data-from")+" "+$(buttonthis).attr("data-name"));var get_parseServer=1
if(parseInt(getCookie("parseServer"))>1){get_parseServer=parseInt(getCookie("parseServer"));}
$.toast('正在连接解析'+get_parseServer+'....')
var this_players_url_arr=players_url[$(buttonthis).attr("data-from")];var this_parseServer_url=this_players_url_arr[get_parseServer+1];if(this_parseServer_url=="-"){this_parseServer_url="";}
$("#iframe_palyer").attr("src",this_parseServer_url+$(buttonthis).attr("data-url"));localStorage_played($(buttonthis).attr("data-jishu"),$(buttonthis).attr("data-url"),JSON_PlaysThisUrl[json_i]);}
function localStorage_update_played(){var str_json_get_played=""+localStorage.getItem("played");var json_rows_temp=JSON.parse(str_json_get_played);var json_limitlength=getJsonLength(json_rows_temp);$("#Played_Show_li").empty();if(str_json_get_played==null||str_json_get_played==""||str_json_get_played=="null"||str_json_get_played=="[]"){$("#list_played").hide();$(".No_played").show();}else{$(".No_played").hide();$("#list_played").show();$("#page_played #listpic").show();for(var json_i=0;json_i<json_limitlength;json_i++){Json_To_piclist_html(json_rows_temp[json_i],json_i,"#Played_Show_li","played");}}
Check_and_modify();}
function localStorage_played(str_jishu,str_url,jsondata){jsondata['played_jishu']=str_jishu;jsondata['str_url']=str_url;var is_has_Exist=0;var str_get_played=localStorage.getItem("played")
if(str_get_played==null){localStorage.setItem("played","["+JSON.stringify(jsondata)+"]");}else{jsonstr_get_played=JSON.parse(str_get_played);var str_news_palyer="";$.each(jsonstr_get_played,function(){if(this.vod_id==jsondata.vod_id){if(str_jishu==""){jsondata['played_jishu']=this.played_jishu;jsondata['str_url']=this.str_url;}}else{if(str_news_palyer==""){str_news_palyer=JSON.stringify(this);}else{str_news_palyer=str_news_palyer+','+JSON.stringify(this);}}});str_news_palyer=JSON.stringify(jsondata)+','+str_news_palyer;str_news_palyer="["+str_news_palyer+"]";str_news_palyer=str_news_palyer.replace("},]","}]");str_news_palyer=str_news_palyer.replace("[, {","[,{");localStorage.setItem("played",str_news_palyer);}
localStorage_update_played();}
function localStorage_del_played(){localStorage.removeItem("played");localStorage_update_played();$.toast("观看记录已清空");}
function localStorage_searchwd(searchwd){if(searchwd){var getItemSearchwd=""+localStorage.getItem("searchwd");var arr_searchwd=getItemSearchwd.split("$$$");var temp_words="";$.each(arr_searchwd,function(){if(this!=searchwd&&this){if(temp_words!=""){temp_words=temp_words+"$$$"+this;}else{temp_words=this;}}});if(temp_words!=""){localStorage.setItem("searchwd",temp_words);}
var getItemSearchwd=""+localStorage.getItem("searchwd");var arr_searchwd=getItemSearchwd.split("$$$");var temp="";if(getItemSearchwd.length<100000||arr_searchwd.length<15){if(localStorage.getItem("searchwd")=="null"||localStorage.getItem("searchwd")==null){localStorage.setItem("searchwd",searchwd);}
else{localStorage.setItem("searchwd",searchwd+"$$$"+localStorage.getItem("searchwd"));}}else{localStorage.setItem("searchwd",searchwd+"$$$"+getItemSearchwd.replace("$$$"+arr_searchwd[arr_searchwd.length-1],""));}
localStorage_update_searchwd();}}
localStorage_update_searchwd();function localStorage_update_searchwd(){var temphtml="搜索历史：";var temp_seadrchwd=localStorage.getItem("searchwd");if(temp_seadrchwd){arr_searchwd=temp_seadrchwd.split("$$$");$.each(arr_searchwd,function(){if(this&&this!="null"){temphtml=temphtml+"<span>"+this+"</span> ";}});$("#YourKeywords").html(temphtml+"[<a href='javascript:localStorage_del_searchwd();'>删除</a>]<br />");}}
function localStorage_del_searchwd(){localStorage.removeItem("searchwd");$("#YourKeywords").empty();}
function getJsonLength(jsonData){var jsonLength=0;for(var item in jsonData){jsonLength++;}
return jsonLength;}
var add_tr;function HengShuPing(){if(window.orientation==180||window.orientation==0){$("#No_hengping1").after(add_tr);$("body").removeClass("HengPing");$("body").addClass("ShuPing");$("#page-loader .loader_logo").css("margin-top","40%");}
if(window.orientation==90||window.orientation==-90){$("body").removeClass("ShuPing");$("body").addClass("HengPing");add_tr=$(".No_hengping1").detach();$("#page-loader .loader_logo").css("margin-top","10%");}}
HengShuPing();window.addEventListener("onorientationchange"in window?"orientationchange":"resize",HengShuPing,false);var int_setInterval1;if(window.location.hash=="#page-loader"||window.location.hash==""){int_setInterval1=setInterval(function(){$('.loader_jump span').html($('.loader_jump span').html()-1);if($('.loader_jump span').html()<=0){gotoindex();}},1000);}
function gotoindex(){int_setInterval1=window.clearInterval(int_setInterval1);$.router.load("#page-index");}
var clipboard=new ClipboardJS('.btn_copy');clipboard.on('success',function(e){$.toast("复制成功，你可以粘贴到别处了");e.clearSelection();});clipboard.on('error',function(e){$.toast("复制失败，请留言反馈给我们");});$(document).on('click','.KaifaZhong',function(){$.toast("这个功能还不能使用，正在加紧升级中");});$(document).on('click','.reloadapp',function(){var arr_url=window.location.href.split("#");$.toast('App重载中..');window.location.href=arr_url[0];});$(document).on('click','.FAQshebei',function(){$.alert('<div style="text-align: left;"><b>随便选个即可。</b><br/>如需同账号多设备登录,请选择不同的设备名登录。<br/>TV版使用预留设备(4)</div>','设备选择说明');});function Show_device_Select(){if($("#login_deviceID_list").css("display")=="none"){$("#login_deviceID_list").show();$("#login_deviceID").empty();}else{$("#login_deviceID_list").hide();}}
function parseServer(buttonthis){setCookie("parseServer",$(buttonthis).attr("data-server"));set_parseServer();$.toast("解析切换成功，重新选集后生效");}
set_parseServer();function set_parseServer(){var needsetid=getCookie("parseServer");if(needsetid==""){needsetid=1;}
$(".parseServerbuttons   a").removeClass("button-fill");$(".parseServerbuttons  [data-server='"+needsetid+"']").addClass("button-fill");}
function setCookie(cname,value){var Days=30;var exp=new Date();exp.setTime(exp.getTime()+Days*24*60*60*1000);document.cookie=cname+"="+escape(value)+";expires="+exp.toGMTString()+";path=/";}
function getCookie(cname){var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i].trim();if(c.indexOf(name)==0)return c.substring(name.length,c.length);}
return"";}
function u_reg(){var user_name=$.trim($("#u_reg input[name='user_name']").val());var uid=$.trim($("#u_reg input[name='uid']").val());var user_email=$.trim($("#u_reg input[name='user_email']").val());var user_pwd=$.trim($("#u_reg input[name='user_pwd']").val());var user_pwd2=$.trim($("#u_reg input[name='user_pwd2']").val());if(uid==""){$.toast("请填写邀请码");}
else if(user_name==""){$.toast("请填写用户名");}
else if(user_email==""){$.toast("请填写邮箱");}
else if(user_pwd==""){$.toast("请输入新密码");}
else if(user_pwd2==""){$.toast("请输入两次");}
else if(user_name.length<6){$.toast("用户名不能低于6个字");}
else if(user_pwd2.length<6){$.toast("密码太短了6位以上哦");}
else if(user_pwd!=user_pwd2){$.toast("两次密码填写不一致");}
else{$.ajax({url:api_url+"/api.php?ac=u_reg",type:"post",dataType:"json",data:$('#u_reg').serialize(),beforeSend:function(){$.toast('正在提交...')},success:function(r){if(r.code==1){$.confirm("请记住您的：<br/>用户名："+user_name+"<br/> 密码"+user_pwd2,'注册成功',function(){u_auto_upgede_checkendtime();gotopage("#page-index");},function(){u_auto_upgede_checkendtime();gotopage("#page-index");});localStorage.removeItem("u_info");localStorage.setItem("u_info",JSON.stringify(r));set_getinfo(0,0);}
else{$.toast("提示："+r.code+" "+r.msg);}},error:function(){$.toast("网络出了一点问题");},complete:function(){}});}}
function u_findpass(){var user_name=$.trim($("#u_findpass input[name='user_name']").val());var user_question=$.trim($("#u_findpass input[name='user_question']").val());var user_answer=$.trim($("#u_findpass input[name='user_answer']").val());var user_pwd=$.trim($("#u_findpass input[name='user_pwd']").val());var user_pwd2=$.trim($("#u_findpass input[name='user_pwd2']").val());if(user_name==""){$.toast("用户名要填写");}
else if(user_question==""){$.toast("请选或输入密保问题");}
else if(user_answer==""){$.toast("请填写密保答案");}
else if(user_pwd==""){$.toast("请输入新密码");}
else if(user_pwd2==""){$.toast("请输入两次");}
else if(user_pwd2.length<6){$.toast("密码太短了6位以上哦");}
else if(user_pwd!=user_pwd2){$.toast("两次密码填写不一致");}else{$.ajax({url:api_url+"/api.php?ac=u_findpass",type:"post",dataType:"json",data:$('#u_findpass').serialize(),beforeSend:function(){$.toast('正在提交...')},success:function(r){if(r.code==1){$.alert("密码重设成功,新密码是：<br/>"+user_pwd2);}
else{$.toast("提示："+r.code+" "+r.msg);}},error:function(){$.toast("网络出了一点问题");},complete:function(){}});}}
function u_login_pin(){var randomPin=$.trim($("#form_login_pin input[name='randomPin']").val());$.ajax({url:api_url+"/api.php?ac=u_login_pin&randomPin="+randomPin,type:"post",dataType:"json",xhrFields:{withCredentials:true},data:$('#userinfo_local').serialize(),beforeSend:function(){$.toast('登录中...')},success:function(r){if(r.code==1){$.toast("快捷登录成功");$(".end_form_login_pin").html("你要登录的快捷码 "+randomPin+" ，设备如果没有自动登录请检查是否输入正确");set_getinfo(0,0);}
else{$.toast("有问题"+r.msg);}},error:function(){$.toast("网络出了一点问题");},complete:function(){}});}
function u_login(){var user_name=$.trim($("#u_login input[name='user_name']").val());var user_pwd=$.trim($("#u_login input[name='user_pwd']").val());var user_random=$("#u_login input[name='user_random']:checked").val();if(user_name==""||user_pwd==""){$.toast("请填写用户名和密码");}else{$.ajax({url:api_url+"/api.php?ac=u_login",type:"post",dataType:"json",data:$('#u_login').serialize(),beforeSend:function(){$.toast('登录中...')},success:function(r){if(r.code==1){$.toast("登录成功");localStorage.removeItem("u_info");localStorage.setItem("u_info",JSON.stringify(r));set_getinfo(0,0);u_auto_upgede_checkendtime();gotopage("#page-index");}
else{$.toast("用户名或者密码错误");}},error:function(){$.toast("网络出了一点问题");},complete:function(){}});}}
function gbook_list(){$.ajax({url:api_url+"/api.php?ac=gbook_list",type:"post",dataType:"json",xhrFields:{withCredentials:true},data:$('#userinfo_local').serialize(),beforeSend:function(){$.toast('正在请求数据...')},success:function(r){if(r.code==1){localStorage.setItem("gbook_list",JSON.stringify(r));$.toast("加载成功");var gbook_list=JSON.parse(localStorage.getItem("gbook_list"));$("#gbook_list_show").empty();$.each(gbook_list.list,function(i){$("#gbook_list_html .card-content-inner").html(this["gbook_name"]+"["+format(this["gbook_time"])+"]:<br> "+this["gbook_content"]);if(this["gbook_reply_time"]==""){$("#gbook_list_html .card-footer").html("暂未回复");}else{$("#gbook_list_html .card-footer").html("管理员回复 ["+format(this["gbook_reply_time"])+"]:"+this["gbook_reply"]);}
$("#gbook_list_show").append($("#gbook_list_html").html());});}
else{$.toast("提示："+r.code+" "+r.msg);}},error:function(){$.toast("网络出了一点问题");},complete:function(){}});}
function add0(m){return m<10?'0'+m:m}
function format(timestamp){var time=new Date(parseInt(timestamp)*1000);var year=time.getFullYear();var month=time.getMonth()+1;var date=time.getDate();var hours=time.getHours();var minutes=time.getMinutes();var seconds=time.getSeconds();return year+'-'+add0(month)+'-'+add0(date)+' '+add0(hours)+':'+add0(minutes)+':'+add0(seconds);}
function gbook_save(){var gbook_content=$.trim($("#gbook_save textarea[name='gbook_content']").val());if(gbook_content.length<5){$.toast("留言内容太短了");}else if(gbook_content.length>150){$.toast("留言内容太多了，最多150个字哦");}else{$.ajax({url:api_url+"/api.php?ac=gbook_save",type:"post",dataType:"json",data:$('#gbook_save').serialize(),beforeSend:function(){$.toast('正在提交...')},success:function(r){if(r.code==1){$.toast("提示："+r.msg);}
else{$.toast("提示："+r.code+" "+r.msg);}},error:function(){$.toast("网络出了一点问题");},complete:function(){}});}}
u_auto_upgede_checkendtime();function u_auto_upgede_checkendtime(){if(getCookie("user_id")>1){var u_info=JSON.parse(localStorage.getItem("u_info"));if(u_info.user_end_time<1){u_upgrade(vip_auto_upgrade,0);}else{var now_timestamp3=Date.parse(new Date());now_timestamp3=now_timestamp3/1000
if(u_info.user_end_time<now_timestamp3&&u_info.user_end_time>1){$.confirm('是否去续费','会员过期',function(){gotopage("#page_u_upgrade");},function(){$.toast("会员过期无法观影哦");});}}}}
function u_upgrade(str_long,int_return_alert){if(str_long!=""||str_long!=null){$.ajax({url:api_url+"/api.php?ac=u_upgrade&long="+str_long,type:"post",dataType:"json",data:$('#userinfo_local').serialize(),beforeSend:function(){$.toast('升级中...')},success:function(r){if(r.code==1){if(int_return_alert>0){$.toast("升级/续费成功");}
set_getinfo(0,1);}
else{if(int_return_alert>0){$.toast("提示："+r.code+r.msg);}}},error:function(){$.toast("网络出了一点问题");},complete:function(){}});}}
function u_upgrade_confirm(str_long){var confirmtxt="";switch(str_long){case"day":confirmtxt="你确定用"+vip_price_day+"积分兑换一天的会员吗？";break;case"week":confirmtxt="你确定用"+vip_price_week+"积分兑换一周的会员吗？";break;case"month":confirmtxt="你确定用"+vip_price_month+"积分兑换一月的会员吗？";break;case"year":confirmtxt="你确定用"+vip_price_year+"积分兑换一年的会员吗？";break;}
$.confirm(confirmtxt,function(){u_upgrade(str_long,1);});}
function u_update(){var user_pwd=$.trim($("#u_update input[name='user_pwd']").val());var user_pwd1=$.trim($("#u_update input[name='user_pwd1']").val());var user_pwd2=$.trim($("#u_update input[name='user_pwd2']").val());var str_alert;if(user_pwd==""){$.toast("请填写密码");}else if(user_pwd1!=user_pwd2){$.toast("两次密码填写不一致");}
else{$.ajax({url:api_url+"/api.php?ac=u_update",type:"post",dataType:"json",data:$('#u_update').serialize(),beforeSend:function(){$.toast('登录中...')},success:function(r){if(r.code==1){$(".user_pwd").val("");$(".user_pwd1").val("");$(".user_pwd2").val("");set_getinfo(0,1);if(user_pwd2!=""){$.alert("修改成功,您修改了密码,新密码是：<br/>"+user_pwd2);}else{$.alert("修改成功");}}
else{$.toast("提示："+r.msg);}},error:function(){$.toast("网络出了一点问题");},complete:function(){}});}}
if(window.location.hash=="#page-loader"||window.location.hash==""){set_getinfo(0,0);}else{set_getinfo(1,0);}
function set_getinfo(int_go_to_login,int_isgetnew){var u_info=JSON.parse(localStorage.getItem("u_info"));if(u_info==null){$(".notlogin").show();$(".logined").hide();if(int_go_to_login>0){$.toast("请先登录");window.location.href="#page-login";}}else{$(".notlogin").hide();$(".logined").show();if(int_isgetnew>0){u_info=JSON.parse(localStorage.getItem("u_info"));$.ajax({url:api_url+"/api.php?ac=u_login&user_only_getinfo=1&user_name="+u_info.user_name,type:"post",dataType:"json",xhrFields:{withCredentials:true},data:$('#userinfo_local').serialize(),success:function(r){if(r.code==1){localStorage.removeItem("u_info");localStorage.setItem("u_info",JSON.stringify(r));set_userinfo();}
else{console.log(r.msg);}},error:function(){console.log("后台获取用户信息失败");}});}else{set_userinfo();}}}
function u_fav_add(vod_id){$.ajax({url:api_url+"/api.php?ac=u_fav_add&vod_id="+vod_id,type:"post",dataType:"json",data:$('#userinfo_local').serialize(),success:function(r){if(r.code==1){$.toast(r.msg);u_fav_list();}
else{console.log(r.msg);}},error:function(){console.log("后台点击收藏失败");}});}
function u_fav_list(){var temp_json=[];$.ajax({url:api_url+"/api.php?ac=u_fav_list",type:"post",dataType:"json",data:$('#userinfo_local').serialize(),success:function(r){if(r.code==1){localStorage.removeItem("u_fav_list");$("#fav_Show_list").empty();$.each(r.list,function(){temp_json.push(this.vod_info);});localStorage.setItem("u_fav_list",""+JSON.stringify(temp_json));localStorage_update_fav();}
else{console.log(r.msg);}},error:function(){console.log("收藏夹列表获取失败");}});}
function localStorage_update_fav(){var str_json_get_played=""+localStorage.getItem("u_fav_list");var json_rows_temp=JSON.parse(str_json_get_played);var json_limitlength=getJsonLength(json_rows_temp);$("#fav_Show_li").empty();if(str_json_get_played==null||str_json_get_played==""||str_json_get_played=="null"||str_json_get_played=="[]"){$("#list_fav").hide();$(".No_fav").show();}else{$(".No_fav").hide();$("#list_fav").show();$("#page_fav #listpic").show();for(var json_i=0;json_i<json_limitlength;json_i++){Json_To_piclist_html(json_rows_temp[json_i],json_i,"#fav_Show_li","u_fav_list");}}
Check_and_modify();}
function u_fav_del(vod_id){$.confirm('确定要删除收藏?',function(){$.ajax({url:api_url+"/api.php?ac=u_fav_del&vod_id="+vod_id,type:"post",dataType:"json",data:$('#userinfo_local').serialize(),success:function(r){if(r.code==1){$.toast("删除成功");u_fav_list();}
else{console.log(r.msg);}},error:function(){console.log("添加收藏失败");}});});}
function Check_and_modify(){var str_get="";var json_rows=null;var json_length=0;var i=0;str_get=""+localStorage.getItem("u_fav_list");json_rows=JSON.parse(str_get);json_length=getJsonLength(json_rows);$(".addfav").show();$(".delfav").hide();if(str_get!=null&&str_get!=""&&str_get!="null"&&str_get!="[]"){for(i=0;i<json_length;i++){$(".vodid_"+json_rows[i].vod_id+"  .addfav").hide();$(".vodid_"+json_rows[i].vod_id+"  .delfav").show();}}
json_rows=null;str_get=""+localStorage.getItem("played");json_rows=JSON.parse(str_get);json_length=getJsonLength(json_rows);$(".nextpalyed").empty();if(str_get!=null&&str_get!=""&&str_get!="null"&&str_get!="[]"){for(i=0;i<json_length;i++){if(json_rows[i].played_jishu){$(".vodid_"+json_rows[i].vod_id+" .nextpalyed").html("上次播放："+json_rows[i].played_jishu);}else{$(".vodid_"+json_rows[i].vod_id+" .nextpalyed").empty();}}}}
set_userinfo();function set_userinfo(){var u_info=JSON.parse(localStorage.getItem("u_info"));$(".user_name").html(u_info.user_name);$(".group_name").html(u_info.group_name);$(".user_end_time").html(format(u_info.user_end_time));$(".user_name_input").val(u_info.user_name);$(".user_id_input").val(u_info.user_id);$(".user_email").val(u_info.user_email);$(".user_question").val(u_info.user_question);$(".user_answer").val(u_info.user_answer);$(".user_points").html(u_info.user_points);$(".user_points_froze").html(u_info.user_points_froze);$(".user_reg_time").html(u_info.user_reg_time);$(".user_last_login_time").html(u_info.user_last_login_time);$(".user_pid").html(u_info.user_pid);$(".user_pid_2").html(u_info.user_pid_2);$(".user_pid_3").html(u_info.user_pid_3);$(".user_loginpin").html(u_info.user_loginpin);$(".local_user_id").val(u_info.user_id);$(".local_user_pwd").val(u_info.user_pwd);$(".local_page_random").val(u_info.local_page_random);}
$(document).on('click','.x_user_pwd',function(){if($('.user_pwd1_2').css('display')=="none"){$(".x_user_pwd").html("取消");$(".user_pwd1_2").show();$(".user_pwd").attr("placeholder","请输入旧密码");$(".user_pwd1").val("");$(".user_pwd2").val("");}else{$(".x_user_pwd").html("修改");$(".user_pwd").attr("placeholder","请输入密码");$(".user_pwd1_2").hide();$(".user_pwd1").val("");$(".user_pwd2").val("");}});$(document).on('click','.x_user_question',function(){var buttons1=[{text:'请选择一个问题',label:true},{text:'您印象最深的老师的名字是？',onClick:function(){$(".user_question_forselect").val("您印象最深的老师的名字是？");$(".user_question_forselect").attr("readonly","readonly");}},{text:'您的第一辆车的型号是？',onClick:function(){$(".user_question_forselect").val("您印象最深的老师的名字是？");$(".user_question_forselect").attr("readonly","readonly");}},{text:'您最喜爱的宠物的名字是？',onClick:function(){$(".user_question_forselect").val("您最喜爱的宠物的名字是？");$(".user_question_forselect").attr("readonly","readonly");}},{text:'您父母认识的地点是？',onClick:function(){$(".user_question_forselect").val("您父母认识的地点是？");$(".user_question_forselect").attr("readonly","readonly");}},{text:'您初恋的名字是？',onClick:function(){$(".user_question_forselect").val("您初恋的名字是？");$(".user_question_forselect").attr("readonly","readonly");}},{text:'您和您的伴侣认识的地址点是？',onClick:function(){$(".user_question_forselect").val("您和您的伴侣认识的地址点是？");$(".user_question_forselect").attr("readonly","readonly");}},{text:'您幼儿园校园名字是？',onClick:function(){$(".user_question_forselect").val("您幼儿园校园名字是？");$(".user_question_forselect").attr("readonly","readonly");}},{text:'您的一个QQ号码是？',onClick:function(){$(".user_question_forselect").val("您的一个QQ号码是？");$(".user_question_forselect").attr("readonly","readonly");}},{text:'您的第一个手机号码是？',onClick:function(){$(".user_question_forselect").val("您的第一个手机号码是？");$(".user_question_forselect").attr("readonly","readonly");}}];var buttons3=[{text:'---自定义一个问题---',color:'danger',onClick:function(){$(".user_question_forselect").val("");$(".user_question_forselect").removeAttr("readonly");}}];var buttons2=[{text:'取消',bg:'danger'}];var groups=[buttons1,buttons3,buttons2];$.actions(groups);});
